version: "3"

services:
  flask:
    network_mode: "service:db"
    image: python:3.10.5
    container_name: flask
    restart: unless-stopped
    stdin_open: true
    build: .
    command: flask run --host=0.0.0.0
    environment:
      - FLASK_APP=server.py
      - DEV_DATABASE_URL=mysql+pymysql://user:secret@localhost:3306/userparameters
  celery:
    network_mode: "service:db"
    build: .
    container_name: 'celery'
    command: celery -A app.celery worker --loglevel=info
    environment:
      - DEV_DATABASE_URL=mysql+pymysql://user:secret@localhost:3306/userparameters
  db:
    container_name: db
    image: mysql:latest
    restart: unless-stopped
    command: --init-file /init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: userparameters
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306
      - 5000:5000
    volumes:
      - ./init.sql:/init.sql
  redis:
    image: redis
    restart: always
    container_name: 'redis'
    command: redis-server
    ports:
      - 6379:6379